# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: golang-pipeline
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.22  # Исправьте версию на актуальную
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: go test ./...

  deploy:
    name: Push to Docker Hub
    needs: test
    if: github.ref == 'refs/heads/main'  # Теперь будет работать для main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_ZAKAB }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - run: docker build -t your-image . && docker push your-image
